//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosAAlvares
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cuentas
    {
        [Key]
        public int IdCuenta { get; set; }
        [ForeignKey("Clientes")]
        public int IdCliente { get; set; }
        [ForeignKey("Entidades")]
        public int IdEntidad { get; set; }
        public string NumCuenta { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        [ForeignKey("TiposCuenta")]
        public Nullable<int> IdTipoCuenta { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Entidades Entidades { get; set; }
        
        public virtual TiposCuenta TiposCuenta { get; set; }
    }
}
