//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosAAlvares
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Prestamos
    {
        [Key]
        public int IdPrestamo { get; set; }
        [ForeignKey("Clientes")]
        public int IdCliente { get; set; }
        public Nullable<decimal> Importe { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
